apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-kiatp
  name: hpa-kiatp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-web
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20