name: kiattiphan-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check server-info
        run: lsb_release -a

      - name: git checkout
        run: git clone https://github.com/kiatp/math24.git

      - name: docker login
        run: docker login -u kiatp -p ${{ secrets.DOCKER_KIATP }}

      - name: build image
        run: |
          cd math24/image
          docker build -t project-lab:5.0.0 .

      - name: docker tag
        run: docker tag project-lab:5.0.0 kiatp/project-lab:5.0.0

      - name: docker push
        run: docker push kiatp/project-lab:5.0.0